name: Continuous Integration Workflow

on:
  push:
    branches: 
      - main

jobs:
  setup_and_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20 ]
    name: in Node.js ${{ matrix.node }} environment
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run check